### ISSUE TITLE
can you upload the trained model in test?

### ISSUE THREAD

**Issue by tuananh** [JoeDoyle23/fasttextjs#1]
i tested it with other trained datasets from fasttext website but it crashed (js error).

very cool project btw. 👍

**Comment by JoeDoyle23** [comment]
The models I'm testing against are part of a commercial project for my job and I'm not comfortable sharing them. I'll see about getting compatibility with the models posted on the main FastText website.

Currently the code is setup to read in ftz files, or the "compressed" format. Those should load fine. You can find some at https://fasttext.cc/docs/en/supervised-models.html#content listed under the "compressed" rows.

**Comment by tuananh** [comment]
Ah the first one i tested didn't work. but amazon full review seems to work fine. I just leave it here so if others stumbled, they may find it useful.
